

services:
  app:
    build:
      context: .
    ports:
      - "3500:3001"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
    command: >
      sh -c "npm run start"

  first-project-postgres:
    image: postgres:16.1
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
      POSTGRES_DB: '${POSTGRES_DB:-first-project}'
    env_file:
      - .env
    volumes:
      - first-project-api-db:/var/lib/postgresql/first-project
    restart: on-failure

  first-project-redis:
    image: redis:7.2.3
    ports:
      - '${REDIS_PORT:-6379}:6379'
    restart: unless-stopped

  first-project-s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "8000:9000"
      - "8001:9001"
    volumes:
      - /first-project-api-s3-data:/usr/src/app/s3
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure

volumes:
  first-project-api-db:
  first-project-api-s3: