export const CarBrand = [
  {
    brand: 'Audi',
    models: ['A1', 'A2', 'A3', 'A4', 'A5', 'A6'],
  },
  {
    brand: 'BMW',
    models: [
      '1 Series',
      '2 Series',
      '3 Series',
      '4 Series',
      '5 Series',
      '6 Series',
      '7 Series',
    ],
  },
  {
    brand: 'Chevrolet',
    models: ['Aveo', 'Camaro', 'Cobalt', 'Cruze', 'Impala'],
  },
  {
    brand: 'Ford',
    models: ['EcoSport', 'Escape', 'Explorer', 'Fiesta', 'Focus'],
  },
  { brand: 'Honda', models: ['Accord', 'Civic', 'CR-V', 'Fit', 'HR-V'] },
  { brand: 'Hyundai', models: ['Accent', 'Elantra', 'i10', 'i20', 'i30'] },
  { brand: 'Kia', models: ['Cadenza', 'Forte', 'Optima', 'Rio', 'Soul'] },
  { brand: 'Mazda', models: ['CX-3', 'CX-5', 'CX-9', 'Mazda2', 'Mazda3'] },
  {
    brand: 'Mercedes-Benz',
    models: ['A-Class', 'B-Class', 'C-Class', 'E-Class', 'S-Class'],
  },
  {
    brand: 'Nissan',
    models: ['Altima', 'Maxima', 'Sentra', 'Versa', 'X-Trail'],
  },
  {
    brand: 'Toyota',
    models: ['Camry', 'Corolla', 'Highlander', 'Rav4', 'Yaris'],
  },
  {
    brand: 'Volkswagen',
    models: ['Arteon', 'Golf', 'Jetta', 'Passat', 'Tiguan'],
  },
  { brand: 'Volvo', models: ['S60', 'S90', 'V60', 'V90', 'XC60'] },
  { brand: 'Tesla', models: ['Model 3', 'Model S', 'Model X', 'Model Y'] },
  {
    brand: 'Subaru',
    models: ['BRZ', 'Forester', 'Impreza', 'Legacy', 'Outback'],
  },
  {
    brand: 'Mitsubishi',
    models: ['Eclipse', 'Lancer', 'Mirage', 'Outlander', 'Pajero'],
  },
  { brand: 'Lexus', models: ['ES', 'GS', 'IS', 'LS', 'NX'] },
  { brand: 'Infiniti', models: ['Q50', 'Q60', 'Q70', 'QX50', 'QX60'] },
  { brand: 'Acura', models: ['ILX', 'MDX', 'RDX', 'RLX', 'TLX'] },
  {
    brand: 'Buick',
    models: ['Enclave', 'Encore', 'Envision', 'LaCrosse', 'Regal'],
  },
  { brand: 'Cadillac', models: ['ATS', 'CT6', 'CTS', 'Escalade', 'XT5'] },
  { brand: 'Chrysler', models: ['300', 'Pacifica', 'Voyager'] },
  { brand: 'Dodge', models: ['Challenger', 'Charger', 'Durango', 'Journey'] },
  {
    brand: 'Jeep',
    models: ['Cherokee', 'Compass', 'Grand Cherokee', 'Renegade', 'Wrangler'],
  },
  { brand: 'Ram', models: ['1500', '2500', '3500'] },
  { brand: 'Fiat', models: ['500', '500L', '500X', 'Panda', 'Tipo'] },
  { brand: 'Alfa Romeo', models: ['Giulia', 'Stelvio'] },
  { brand: 'Peugeot', models: ['108', '208', '308', '508', '2008'] },
  {
    brand: 'Renault',
    models: ['Clio', 'Duster', 'Kadjar', 'Koleos', 'Megane'],
  },
  { brand: 'Citroen', models: ['Berlingo', 'C3', 'C4', 'C5', 'Jumpy'] },
  { brand: 'Opel', models: ['Adam', 'Astra', 'Corsa', 'Insignia', 'Mokka'] },
  { brand: 'Seat', models: ['Arona', 'Ibiza', 'Leon', 'Tarraco'] },
  { brand: 'Skoda', models: ['Fabia', 'Karoq', 'Octavia', 'Superb'] },
  { brand: 'Suzuki', models: ['Baleno', 'Ignis', 'Swift', 'Vitara'] },
  { brand: 'Dacia', models: ['Duster', 'Logan', 'Sandero'] },
  { brand: 'Mini', models: ['Clubman', 'Countryman', 'Hatch', 'Cabrio'] },
  { brand: 'Smart', models: ['ForTwo', 'ForFour'] },
  { brand: 'Jaguar', models: ['E-Pace', 'F-Pace', 'I-Pace', 'XE', 'XF'] },
  {
    brand: 'Land Rover',
    models: [
      'Discovery',
      'Range Rover Evoque',
      'Range Rover Sport',
      'Range Rover Velar',
    ],
  },
  { brand: 'Porsche', models: ['911', 'Cayenne', 'Macan', 'Panamera'] },
  { brand: 'Ferrari', models: ['488', '812', 'GTC4', 'Portofino'] },
  { brand: 'Lamborghini', models: ['Aventador', 'Huracan', 'Urus'] },
  { brand: 'Maserati', models: ['Ghibli', 'Levante', 'Quattroporte'] },
  { brand: 'McLaren', models: ['540C', '570S', '720S'] },
  { brand: 'Bugatti', models: ['Chiron', 'Divo', 'Veyron'] },
  { brand: 'Aston Martin', models: ['DB11', 'DBS', 'Vantage'] },
  { brand: 'Lotus', models: ['Elise', 'Evora', 'Exige'] },
  { brand: 'Rolls-Royce', models: ['Cullinan', 'Dawn', 'Ghost', 'Phantom'] },
];
