export enum CarBrand {
  BMW = 'BMW',
  AUDI = 'AUDI',
  MERCEDES = 'MERCEDES',
  TOYOTA = 'TOYOTA',
  HONDA = 'HONDA',
  FORD = 'FORD',
  CHEVROLET = 'CHEVROLET',
  NISSAN = 'NISSAN',
  VOLKSWAGEN = 'VOLKSWAGEN',
  HYUNDAI = 'HYUNDAI',
  KIA = 'KIA',
  PEUGEOT = 'PEUGEOT',
  RENAULT = 'RENAULT',
  MAZDA = 'MAZDA',
  SUZUKI = 'SUZUKI',
  MITSUBISHI = 'MITSUBISHI',
  CITROEN = 'CITROEN',
  SUBARU = 'SUBARU',
  CHRYSLER = 'CHRYSLER',
  JEEP = 'JEEP',
  DODGE = 'DODGE',
  VOLVO = 'VOLVO',
  LAND_ROVER = 'LAND_ROVER',
  PORSCHE = 'PORSCHE',
  JAGUAR = 'JAGUAR',
  FERRARI = 'FERRARI',
  LAMBORGHINI = 'LAMBORGHINI',
  BUGATTI = 'BUGATTI',
  MASERATI = 'MASERATI',
  ASTON_MARTIN = 'ASTON_MARTIN',
  BENTLEY = 'BENTLEY',
  ROLLS_ROYCE = 'ROLLS_ROYCE',
  ALFA_ROMEO = 'ALFA_ROMEO',
  LOTUS = 'LOTUS',
  MCLAREN = 'MCLAREN',
  TESLA = 'TESLA',
  LEXUS = 'LEXUS',
  INFINITI = 'INFINITI',
  ACURA = 'ACURA',
  CADILLAC = 'CADILLAC',
}

export const carModels = {
  [CarBrand.BMW]: ['X5', 'X3', 'M3'],
  [CarBrand.AUDI]: ['A4', 'Q7', 'R8'],
  [CarBrand.MERCEDES]: ['C-Class', 'E-Class', 'S-Class'],
  [CarBrand.TOYOTA]: ['Corolla', 'Camry', 'RAV4'],
  [CarBrand.HONDA]: ['Civic', 'Accord', 'CR-V'],
  [CarBrand.FORD]: ['Fiesta', 'Focus', 'Mustang'],
  [CarBrand.CHEVROLET]: ['Spark', 'Malibu', 'Impala'],
  [CarBrand.NISSAN]: ['Altima', 'Sentra', 'Maxima'],
  [CarBrand.VOLKSWAGEN]: ['Golf', 'Passat', 'Tiguan'],
  [CarBrand.HYUNDAI]: ['Elantra', 'Sonata', 'Tucson'],
  [CarBrand.KIA]: ['Rio', 'Optima', 'Sorento'],
  [CarBrand.PEUGEOT]: ['208', '308', '508'],
  [CarBrand.RENAULT]: ['Clio', 'Megane', 'Kadjar'],
  [CarBrand.CITROEN]: ['C3', 'C4', 'C5'],
  [CarBrand.SUZUKI]: ['Swift', 'Vitara', 'Jimny'],
  [CarBrand.MAZDA]: ['2', '3', '6'],
  [CarBrand.SUBARU]: ['Impreza', 'Forester', 'Outback'],
  [CarBrand.MITSUBISHI]: ['Lancer', 'Outlander', 'Pajero'],
  [CarBrand.TESLA]: ['Model S', 'Model 3', 'Model X'],
  [CarBrand.JEEP]: ['Wrangler', 'Cherokee', 'Grand Cherokee'],
  [CarBrand.DODGE]: ['Charger', 'Challenger', 'Durango'],
  [CarBrand.VOLVO]: ['S60', 'XC60', 'XC90'],
  [CarBrand.LAND_ROVER]: ['Defender', 'Discovery', 'Range Rover'],
  [CarBrand.JAGUAR]: ['XE', 'XF', 'F-Pace'],
  [CarBrand.PORSCHE]: ['911', 'Cayenne', 'Macan'],
  [CarBrand.LEXUS]: ['IS', 'ES', 'RX'],
  [CarBrand.INFINITI]: ['Q50', 'QX60', 'QX80'],
  [CarBrand.ACURA]: ['ILX', 'TLX', 'RDX'],

  [CarBrand.CADILLAC]: ['CT4', 'XT5', 'Escalade'],
  [CarBrand.CHRYSLER]: ['300', 'Pacifica', 'Voyager'],
  [CarBrand.FERRARI]: ['488', 'Portofino', 'Roma'],
  [CarBrand.LAMBORGHINI]: ['Huracan', 'Aventador', 'Urus'],
  [CarBrand.BUGATTI]: ['Chiron', 'Veyron', 'Divo'],
  [CarBrand.MASERATI]: ['Ghibli', 'Levante', 'Quattroporte'],
  [CarBrand.ASTON_MARTIN]: ['DB11', 'Vantage', 'DBS'],
  [CarBrand.BENTLEY]: ['Bentayga', 'Continental', 'Flying Spur'],
  [CarBrand.ROLLS_ROYCE]: ['Phantom', 'Ghost', 'Wraith'],
  [CarBrand.ALFA_ROMEO]: ['Giulia', 'Stelvio', '4C'],
  [CarBrand.LOTUS]: ['Elise', 'Exige', 'Evora'],
  [CarBrand.MCLAREN]: ['570S', '720S', 'P1'],
} ;